services:
  postgres:
    image: postgres:18-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d pg']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    ports:
      - '4983:4983'
    environment:
      MASTERPASS: ${MASTERPASS:-password}
      PG_CONNECTION: postgresql://root:password@postgres:5432/pg
      STORE_PATH: /app/data
    volumes:
      - drizzle-store:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: .
      args:
        GIT_REVISION: ${GIT_REVISION:-dev}
    ports:
      - '8000:8000'
    environment:
      - UPLOADS_DIR=/app/uploads
      - PG_CONNECTION=postgresql://root:password@postgres:5432/pg
      - APP_BASE_URL=http://localhost:8000
      - BETTER_AUTH_URL=http://localhost:8000
      - BETTER_AUTH_SECRET=c94a90989040561858f261455d0e7fde0d905f7a2c39633d17d68b3712edf756
    volumes:
      - passport_uploads:/app/uploads

    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  passport_uploads:
  pgdata:
  drizzle-store:
